# Generated by Django 5.2 on 2025-04-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beforelogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
