# Generated by Django 5.2 on 2025-05-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beforelogin', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
